language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '9'
  - '8'

before_script:
  - npm install

script:
  - npm run lint
  - npm run deploy

after_success:
  - conventional-changelog -p angular -i CHANGELOG.md -s
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
