language: node_js

env:
  global:
  - GH_USER: BartvdWaerden
  - GH_REPO: bartvanderwaerden

cache:
  directories:
    - node_modules

node_js:
  - 'stable'

before_script:
  - npm install

script:
  - npm run lint
  - npm run deploy

after_success:
  - conventional-changelog -p angular -i CHANGELOG.md -s
  - npm run travis-deploy-once "npm run semantic-release"

before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Travis"

deploy:
  provider: pages
  skip-cleanup: true,
  github_token: $github_token
  keep-history: true
  on:
    branch: master

