language: node_js

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '9'
  - '8'
  - '6'
  - '4'

before_script:
  - npm install

script:
  - npm run test
  - npm run deploy

after_success:
  - conventional-changelog -p angular -i CHANGELOG.md -s
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
