language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - ~/.npm
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: public
  on:
    branch: master

after_success:
  - npm install -g travis-deploy-once
  - npm run travis-deploy-once "npm run semantic-release"
  - conventional-changelog -p angular -i CHANGELOG.md -s
