language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: true
node_js:
  - 'stable'
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local_dir: public
  on:
    branch: master
after_success:
  npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
